import './globals.css'
import { Noto_Sans_Thai } from 'next/font/google';

const noto_sans_thai = Noto_Sans_Thai({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'V-manga',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto_sans_thai.className}>
        <div className='bg-green-300/30 p-10'>
          <h1 className='text-3xl text-center font-bold'>V-MANGA</h1>
          <h3 className='text-xl text-green-600/60 text-center font-semibold'>เว็บสำหรับชาว Inu_makI Fandub || inuZilla [อินุซิลล่า]</h3>
          <h3 className='text-xl text-green-600/60 text-center font-semibold'>สร้างขึ้นมาเพื่อใช้ในการโหลดภาพมังงะให้สะดวกสบายมากยิ่งขึ้น!!!</h3>
        </div>
        {children}
      </body>
    </html>
  )
}
